export { default as CartTotals } from "./components/cart-totals"
export { default as DeleteButton } from "./components/delete-button"
export { default as LineItemUnitPrice } from "./components/line-item-unit-price"
export { SubmitButton } from "./components/submit-button" 
export { default as Bancontact } from "./icons/bancontact"
export { default as Ideal } from "./icons/ideal"
export { default as PayPal } from "./icons/paypal"
export { default as PlaceholderImage } from "./icons/placeholder-image"
export { default as Spinner } from "./icons/spinner"